In [11]:
# Import von Packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math

dfTime = pd.read_csv("Material_UE1/time.csv")
dfTemp = pd.read_csv("Material_UE1/Temperatur.csv")
dfStrahlung = pd.read_csv("Material_UE1/Strahlung.csv")

,Year,Month,Day,Hour,DirectInclined,DiffuseInclined,Reflected,GlobalInclined,DirectHoriz,DiffusHoriz,GlobalHoriz,TopOfAtmosphere
0,2005,1,1,0.25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2005,1,1,0.50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2005,1,1,0.75,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2005,1,1,1.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2005,1,1,1.25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
35035,2005,12,31,23.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35036,2005,12,31,23.25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35037,2005,12,31,23.50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35038,2005,12,31,23.75,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35039,2005,12,31,24.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0